%Getting spikes in bins from MEA tools csv files
%Logan Whitehouse
%lswhiteh@iupui.edu

tmp = matlab.desktop.editor.getActive;
cd(fileparts(tmp.Filename));
files = dir('*.csv');
for file = files'
    
    disp(file.name);
    filename = file.name;
    dataTable = importfile(filename);
    
    times = table2array(dataTable(:, 2));
    
    longTime = max(times);
    startTimes = [];
    endTimes = [];
    
    channelmultNums = table2array(dataTable(:, 1:2));
    electrodes = [12:17 21:28 31:38 41:48 51:58 61:68 71:78 82:87];
    electrodes = electrodes';
    bins = [12:17 21:28 31:38 41:48 51:58 61:68 71:78 82:88];
    
    %Establish bin times using longest time recorded
    for i = 0:10:longTime
        startTimes = [startTimes;i];
        endTimes = [endTimes;i+10];
    end
        
    % Get counts for how many spikes in each using histcounts
    channelRepeats = {};
    binCounts = {};
    for i = 1:length(endTimes)
        indexes = channelmultNums(:, 2) >= startTimes(i) & channelmultNums(:, 2) < endTimes(i);
        channelRepeats{i} = channelmultNums(indexes);
        binCounts{i} = [electrodes, histcounts(channelRepeats{i}, bins)'];
    end
   
    % Bring everything together into table that reads easier
    summary = {};
    summary{1} = 'Electrode';
    
    for i = 1:length(startTimes)
        summary{i+1} = strcat('Seconds ', num2str(startTimes(i)), '_', num2str(endTimes(i))); 
    end
    
    for i = 1:length(electrodes)
        summary{1+i, 1} = electrodes(i);
    end
        
    for i = 1:length(startTimes)
        for j = 1:length(electrodes)
            summary{1+j, 1+i} = binCounts{1,i}(j,2);
        end
    end
     
      
    
    % Write to file
    % Have to convert to table first
    summary = cell2table(summary);
    writetable(summary, strcat('spike_counts_', filename));
    
end
    






function dataTable = importfile(filename, startRow, endRow)
    %IMPORTFILE Import numeric data from a text file as a matrix.
    %   UNTITLED = IMPORTFILE(FILENAME) Reads data from text file FILENAME for
    %   the default selection.
    %
    %   UNTITLED = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
    %   STARTROW through ENDROW of text file FILENAME.
    %
    % Example:
    %   Untitled = importfile('5.24.17_11_hippo_SAG.csv', 2, 3116);
    %
    %    See also TEXTSCAN.
    
    % Auto-generated by MATLAB on 2018/02/21 12:33:39
    
    %% Initialize variables.
    delimiter = ',';
    if nargin<=2
        startRow = 2;
        endRow = inf;
    end
    
    %% Format for each line of text:
    %   column1: double (%f)
    %	column2: double (%f)
    %   column3: double (%f)
    %	column4: double (%f)
    %   column5: categorical (%C)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%f%f%f%f%C%[^\n\r]';
    
    %% Open the text file.
    fileID = fopen(filename,'r');
    
    %% Read columns of data according to the format.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for block=2:length(startRow)
        frewind(fileID);
        dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
        for col=1:length(dataArray)
            dataArray{col} = [dataArray{col};dataArrayBlock{col}];
        end
    end
    
    %% Close the text file.
    fclose(fileID);
 
    %% Create output variable
    dataTable = table(dataArray{1:end-1}, 'VariableNames', {'electrode','time','amplitude','threshold','conductance'});
    
    
end
    

